pub mod attribute_commands;
pub mod book_commands;
pub mod chapter_commands;
pub mod entity_commands;
pub mod mention_commands;
pub mod relation_commands;
pub mod stats_commands;
pub mod story_commands;
pub mod universe_commands;
